; Shared PHP settings (base image, dev + prod)
memory_limit = 256M
upload_max_filesize = 20M
post_max_size = 20M
max_execution_time = 60
date.timezone = Asia/Jakarta

opcache.enable = 1
opcache.enable_cli = 0
